Use generated function to compute number of workgroups to be launched.
google/iree pull request #3095
Opened 2020-09-08 20:56 UTC by MaheshRavishankar

The current mechanism of deciding number of workgroups to use for the
launch uses an enumeration of fixed strategies. This is not sufficient
to cover all uses. This commit adds a new mechanism where the
codegeneration passes generate the function to use that when called
from the host side will return the number of workgroups to use. The
arguments to the function are the shapes of the inputs and outputs to
the dispatch region.
Currently this is enabled only for static shapes, since there are some
unresolved issues w.r.t to the dynamic shape case.

2020-09-08 21:26 UTC, benvanik requested changes
Hmm this has an design issue - all of the new result num/operand num/etc attributes cannot exist. The interface bindings are not 1:1 with function operands/results. The signature on the entry point is informational only and cannot be used to reverse the mapping.

There shouldn't be any need to do that, but I'm having trouble finding where in the code the false requirement snuck in.

2020-09-08 21:37 UTC, MaheshRavishankar commented
The operand_num/result_num are not on the interface (since each binding might be for multiple values). They are just on the load/store/placeholder ops. This way I can map back to the Operands/Results of the DispatchState. Happy to try a better way. Lets chat offline.

2020-09-09 21:45 UTC, MaheshRavishankar commented
Please hold off on review for a bit. Going to be pushing some changes that needs some cleanup (comments, documentation, etc.)

2020-09-10 05:23 UTC, MaheshRavishankar commented
This is now ready for review. 
@antiagainst @benvanik @hanhanW

2020-09-10 19:31 UTC, benvanik approved these changes

2020-09-10 19:31 UTC, benvanik commented on iree/compiler/Conversion/LinalgToSPIRV/KernelDispatchUtils.h
> +}  // namespace mlir
nit: vertical whitespace

2020-09-10 19:31 UTC, benvanik commented on iree/compiler/Conversion/HLOToLinalg/HLOToLinalgOnBuffers.cpp
> -  }
nit: we are trying not to do this in IREE code and use braces like in google style

2020-09-10 19:31 UTC, benvanik commented on iree/compiler/Conversion/LinalgToSPIRV/test/split_dispatch_function.mlir
> +  func @kernel() attributes {vkspv.num_workgroups_fn = @kernel__num_workgroups__} {
this is really nice!

2020-09-10 19:31 UTC, benvanik commented on iree/compiler/Dialect/HAL/Target/VulkanSPIRV/VulkanSPIRVTarget.cpp
> +#include "iree/compiler/Dialect/Shape//IR/ShapeOps.h"
double //

2020-09-10 19:31 UTC, benvanik commented on iree/compiler/Dialect/HAL/Target/VulkanSPIRV/VulkanSPIRVTarget.cpp
> +    return returnValue;
nit: add {} here and below

2020-09-10 20:07 UTC, antiagainst approved these changes
Awesome!

2020-09-10 20:07 UTC, antiagainst commented on iree/compiler/Conversion/LinalgToSPIRV/KernelDispatchUtils.cpp
> +    entryPointFn.emitError("enable to find num workgroups fn ") << attr;
unable

2020-09-10 20:07 UTC, antiagainst commented on iree/compiler/Conversion/LinalgToSPIRV/LegalizeNumWorkgroupsFnPass.cpp
> +static PassRegistration<LegalizeNumWorkgroupsFnPass> pass(
Instead of init/legalize, I'd think declare/define would be better. But your choice.

2020-09-11 05:42 UTC, MaheshRavishankar commented
Thanks for the review!

2020-09-15 07:55 UTC, merged