Enable MobileBert test on vulkan and llvmjit.
google/iree pull request #3474
Opened 2020-10-14 16:10 UTC by hanhanW

2020-10-14 16:26 UTC, phoenix-meadowlark requested changes
Could you add a description about what change allowed us to enable these?

2020-10-14 16:26 UTC, phoenix-meadowlark commented on integrations/tensorflow/e2e/BUILD
> +        "iree_llvmjit": ["mobile_bert_squad_test.py"],
Nit: All of the other targets list these in this order.

```suggestion
        "iree_llvmjit": ["mobile_bert_squad_test.py"],
        "iree_vulkan": ["mobile_bert_squad_test.py"],
```

2020-10-14 16:31 UTC, phoenix-meadowlark commented
`iree_llvmjit` and `iree_vulkan` are both failing at head for me.

**LLVM:**
```
*** Received signal 6 ***
*** BEGIN MANGLED STACK TRACE ***
/usr/local/google/home/meadowlark/.pyenv/versions/3.8.3/lib/python3.8/site-packages/tensorflow/python/../libtensorflow_framework.so.2(+0x112a74d)[0x7fe83273b74d]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x14140)[0x7fe910e4f140]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x141)[0x7fe910b60db1]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x123)[0x7fe910b4a537]
/lib/x86_64-linux-gnu/libc.so.6(+0x7e828)[0x7fe910ba3828]
/lib/x86_64-linux-gnu/libc.so.6(+0x85b1a)[0x7fe910baab1a]
/lib/x86_64-linux-gnu/libc.so.6(+0x8684c)[0x7fe910bab84c]
/lib/x86_64-linux-gnu/libc.so.6(+0x8703b)[0x7fe910bac03b]
/dev/shm/bazel-sandbox.19090a49aee87113714d6b0f1be1774a673978988ab65419246c1db550a7e52e/linux-sandbox/106/execroot/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/mobile_bert_squad_tests__mobile_bert_squad_test__target_backends__iree_llvmjit.runfiles/iree_core/bindings/python/pyiree/rt/binding.so(_ZN4iree3hal10HostBufferD0Ev+0x2b)[0x7fe86cdac1fb]
/dev/shm/bazel-sandbox.19090a49aee87113714d6b0f1be1774a673978988ab65419246c1db550a7e52e/linux-sandbox/106/execroot/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/mobile_bert_squad_tests__mobile_bert_squad_test__target_backends__iree_llvmjit.runfiles/iree_core/bindings/python/pyiree/rt/binding.so(iree_vm_ref_release+0x4a)[0x7fe86cdbed9a]
/dev/shm/bazel-sandbox.19090a49aee87113714d6b0f1be1774a673978988ab65419246c1db550a7e52e/linux-sandbox/106/execroot/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/mobile_bert_squad_tests__mobile_bert_squad_test__target_backends__iree_llvmjit.runfiles/iree_core/bindings/python/pyiree/rt/binding.so(+0x1d634c8)[0x7fe86cd814c8]
/dev/shm/bazel-sandbox.19090a49aee87113714d6b0f1be1774a673978988ab65419246c1db550a7e52e/linux-sandbox/106/execroot/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/mobile_bert_squad_tests__mobile_bert_squad_test__target_backends__iree_llvmjit.runfiles/iree_core/bindings/python/pyiree/rt/binding.so(+0x1d69099)[0x7fe86cd87099]
/dev/shm/bazel-sandbox.19090a49aee87113714d6b0f1be1774a673978988ab65419246c1db550a7e52e/linux-sandbox/106/execroot/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/mobile_bert_squad_tests__mobile_bert_squad_test__target_backends__iree_llvmjit.runfiles/iree_core/bindings/python/pyiree/rt/binding.so(+0x1d83cdd)[0x7fe86cda1cdd]
/dev/shm/bazel-sandbox.19090a49aee87113714d6b0f1be1774a673978988ab65419246c1db550a7e52e/linux-sandbox/106/execroot/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/mobile_bert_squad_tests__mobile_bert_squad_test__target_backends__iree_llvmjit.runfiles/iree_core/bindings/python/pyiree/rt/binding.so(+0x1d9c06d)[0x7fe86cdba06d]
/dev/shm/bazel-sandbox.19090a49aee87113714d6b0f1be1774a673978988ab65419246c1db550a7e52e/linux-sandbox/106/execroot/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/mobile_bert_squad_tests__mobile_bert_squad_test__target_backends__iree_llvmjit.runfiles/iree_core/bindings/python/pyiree/rt/binding.so(+0x1d9b939)[0x7fe86cdb9939]
/dev/shm/bazel-sandbox.19090a49aee87113714d6b0f1be1774a673978988ab65419246c1db550a7e52e/linux-sandbox/106/execroot/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/mobile_bert_squad_tests__mobile_bert_squad_test__target_backends__iree_llvmjit.runfiles/iree_core/bindings/python/pyiree/rt/binding.so(iree_vm_bytecode_dispatch+0x1911)[0x7fe86cdb8531]
/dev/shm/bazel-sandbox.19090a49aee87113714d6b0f1be1774a673978988ab65419246c1db550a7e52e/linux-sandbox/106/execroot/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/mobile_bert_squad_tests__mobile_bert_squad_test__target_backends__iree_llvmjit.runfiles/iree_core/bindings/python/pyiree/rt/binding.so(+0x1d9835a)[0x7fe86cdb635a]
/dev/shm/bazel-sandbox.19090a49aee87113714d6b0f1be1774a673978988ab65419246c1db550a7e52e/linux-sandbox/106/execroot/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/mobile_bert_squad_tests__mobile_bert_squad_test__target_backends__iree_llvmjit.runfiles/iree_core/bindings/python/pyiree/rt/binding.so(+0x1d9dcb3)[0x7fe86cdbbcb3]
/dev/shm/bazel-sandbox.19090a49aee87113714d6b0f1be1774a673978988ab65419246c1db550a7e52e/linux-sandbox/106/execroot/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/mobile_bert_squad_tests__mobile_bert_squad_test__target_backends__iree_llvmjit.runfiles/iree_core/bindings/python/pyiree/rt/binding.so(iree_vm_invoke+0x8f)[0x7fe86cdbb9af]
/dev/shm/bazel-sandbox.19090a49aee87113714d6b0f1be1774a673978988ab65419246c1db550a7e52e/linux-sandbox/106/execroot/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/mobile_bert_squad_tests__mobile_bert_squad_test__target_backends__iree_llvmjit.runfiles/iree_core/bindings/python/pyiree/rt/binding.so(_ZN4iree6python9VmContext6InvokeE18iree_vm_function_tRNS0_13VmVariantListES4_+0x3c)[0x7fe86cd4c22c]
/dev/shm/bazel-sandbox.19090a49aee87113714d6b0f1be1774a673978988ab65419246c1db550a7e52e/linux-sandbox/106/execroot/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/mobile_bert_squad_tests__mobile_bert_squad_test__target_backends__iree_llvmjit.runfiles/iree_core/bindings/python/pyiree/rt/binding.so(+0x1d3ee46)[0x7fe86cd5ce46]
/dev/shm/bazel-sandbox.19090a49aee87113714d6b0f1be1774a673978988ab65419246c1db550a7e52e/linux-sandbox/106/execroot/iree_core/bazel-out/k8-opt/bin/integrations/tensorflow/e2e/mobile_bert_squad_tests__mobile_bert_squad_test__target_backends__iree_llvmjit.runfiles/iree_core/bindings/python/pyiree/rt/binding.so(+0x7c1db8)[0x7fe86b7dfdb8]
/usr/local/google/home/meadowlark/.pyenv/versions/3.8.3/bin/python3[0x430e7e]
/usr/local/google/home/meadowlark/.pyenv/versions/3.8.3/bin/python3(_PyObject_MakeTpCall+0x14a)[0x4308fa]
/usr/local/google/home/meadowlark/.pyenv/versions/3.8.3/bin/python3[0x58c3e6]
/usr/local/google/home/meadowlark/.pyenv/versions/3.8.3/bin/python3[0x4c7bfc]
/usr/local/google/home/meadowlark/.pyenv/versions/3.8.3/bin/python3(_PyEval_EvalFrameDefault+0x644b)[0x4c4e9b]
/usr/local/google/home/meadowlark/.pyenv/versions/3.8.3/bin/python3(_PyEval_EvalCodeWithName+0xcce)[0x4c8cee]
/usr/local/google/home/meadowlark/.pyenv/versions/3.8.3/bin/python3(_PyFunction_Vectorcall+0xf9)[0x431399]
/usr/local/google/home/meadowlark/.pyenv/versions/3.8.3/bin/python3(_PyObject_FastCallDict+0x85)[0x4306f5]
/usr/local/google/home/meadowlark/.pyenv/versions/3.8.3/bin/python3(_PyObject_Call_Prepend+0x73)[0x431c63]
/usr/local/google/home/meadowlark/.pyenv/versions/3.8.3/bin/python3[0x477ad0]
/usr/local/google/home/meadowlark/.pyenv/versions/3.8.3/bin/python3(PyObject_Call+0x96)[0x430d86]
/usr/local/google/home/meadowlark/.pyenv/versions/3.8.3/bin/python3(_PyEval_EvalFrameDefault+0x671b)[0x4c516b]
/usr/local/google/home/meadowlark/.pyenv/versions/3.8.3/bin/python3(_PyEval_EvalCodeWithName+0xcce)[0x4c8cee]
/usr/local/google/home/meadowlark/.pyenv/versions/3.8.3/bin/python3(_PyFunction_Vectorcall+0xf9)[0x431399]
/usr/local/google/home/meadowlark/.pyenv/versions/3.8.3/bin/python3(_PyObject_FastCallDict+0x85)[0x4306f5]
/usr/local/google/home/meadowlark/.pyenv/versions/3.8.3/bin/python3(_PyObject_Call_Prepend+0x73)[0x431c63]
/usr/local/google/home/meadowlark/.pyenv/versions/3.8.3/bin/python3[0x477ad0]
/usr/local/google/home/meadowlark/.pyenv/versions/3.8.3/bin/python3(PyObject_Call+0x96)[0x430d86]
/usr/local/google/home/meadowlark/.pyenv/versions/3.8.3/bin/python3(_PyEval_EvalFrameDefault+0x671b)[0x4c516b]
/usr/local/google/home/meadowlark/.pyenv/versions/3.8.3/bin/python3(_PyEval_EvalCodeWithName+0xcce)[0x4c8cee]
/usr/local/google/home/meadowlark/.pyenv/versions/3.8.3/bin/python3(_PyFunction_Vectorcall+0xf9)[0x431399]
/usr/local/google/home/meadowlark/.pyenv/versions/3.8.3/bin/python3[0x4c7bfc]
/usr/local/google/home/meadowlark/.pyenv/versions/3.8.3/bin/python3(_PyEval_EvalFrameDefault+0x657c)[0x4c4fcc]
/usr/local/google/home/meadowlark/.pyenv/versions/3.8.3/bin/python3(_PyEval_EvalCodeWithName+0xcce)[0x4c8cee]
/usr/local/google [...]

2020-10-14 17:37 UTC, hanhanW commented
They are passing on my machine and CI, how do you test it? Could you test on upstream/main? There is a needed patch in MLIR core, so if your submodule version is not bumped, it will fail.

2020-10-14 17:45 UTC, phoenix-meadowlark commented
> They are passing on my machine and CI, how do you test it? Could you test on upstream/main? There is a needed patch in MLIR core, so if your submodule version is not bumped, it will fail.

These tests aren't run by the OSS CI (they have a `"nokokoro"` tag).

I tested this at head in IREE (currently 3ee429afec66cf1c7a1d5f81a70ac2ea2424a2f1) by running `bazel test integrations/tensorflow/e2e:mobile_bert_squad_tests_failing`.

2020-10-14 17:50 UTC, hanhanW commented
Oh I see the reason now. I have a local change in MLIR repo. This needs to wait until @MaheshRavishankar patch is landed and the integration is done. Thanks for catching this, and sorry about this.

2020-10-16 12:40 UTC, hanhanW commented
Hey @phoenix-meadowlark this is ready to land, please take a look. Thanks!

2020-10-16 17:38 UTC, phoenix-meadowlark approved these changes

2020-10-16 17:45 UTC, merged