Update ruy to the latest upstream commit.
google/iree pull request #3479
Opened 2020-10-14 20:41 UTC by bjacob

Rewrite CMakeLists.txt to actually do the correct SIMD flag-setting as
in the upstream BUILD, and to be more correct e.g. declaring all
dependencies even on header-only internal libraries.

The immediate motivation for this is enabling x86 SIMD (AVX/AVX2/AVX512)
code paths.

2020-10-15 07:02 UTC, hanhanW commented
fyi, there is an option to convert it to draft.
![image](https://user-images.githubusercontent.com/6949191/96087974-9515d600-0e79-11eb-878f-7e6589136828.png)

2020-10-15 23:23 UTC, benvanik commented
In ruy's kernel_x86.h the define is `_MSC_VER` (not `__MSC_VER`); like:
`#if (defined __clang__) || (defined _MSC_VER)`

2020-10-15 23:29 UTC, benvanik commented on build_tools/third_party/ruy/CMakeLists.txt
> +if(CMAKE_SYSTEM_PROCESSOR STREQUAL x86_64 OR
apparently it's AMD64 (sometimes); this seems to be the recommended way to handle it:
```
string(TOLOWER "${CMAKE_SYSTEM_PROCESSOR}" _CMAKE_SYSTEM_PROCESSOR_LOWER)
if(_CMAKE_SYSTEM_PROCESSOR_LOWER STREQUAL x86_64 OR
   _CMAKE_SYSTEM_PROCESSOR_LOWER STREQUAL amd64)
```

2020-10-15 23:34 UTC, benvanik requested changes
two minor fixes (one upstream ruy, one here) then it seems to work for me on windows/msvc/avx2!

2020-10-16 15:57 UTC, benvanik approved these changes

2020-10-16 18:44 UTC, merged