Use vector transfer forwarding and dead store elimination in IREE
google/iree pull request #4032
Opened 2020-11-30 21:18 UTC by ThomasRaoux

2020-11-30 22:40 UTC, antiagainst approved these changes
Awesome!

2020-11-30 22:45 UTC, MaheshRavishankar requested changes

2020-11-30 22:45 UTC, MaheshRavishankar commented on iree/compiler/Conversion/Common/Passes.h
> +std::unique_ptr<FunctionPass> createVectorTransferOptimizationPass();
Can we just call this VectorLoadStoreForwardingPass? The name is too generic :)

2020-11-30 23:15 UTC, MaheshRavishankar approved these changes
Looks good! Ill leave the pass name upto you :)

2020-12-01 00:05 UTC, ThomasRaoux commented
> Looks good! Ill leave the pass name upto you :)

Thanks Mahesh, I'll leave it like that for now to be consistent with upstream.

2020-12-01 00:05 UTC, merged