Let Linalg on tensor ops pass LegalizeInputTypes
google/iree pull request #4107
Opened 2020-12-07 17:02 UTC by nicolasvasilache

Assume that all Linalg ops on tensors have legal input types for now.
This allows IREE to ingest Linalg on tensor ops from the frontend and pipe it through.
This is necessary to use Linalg on tensors as a programming model for IREE without relying on HLO.

2020-12-07 22:03 UTC, MaheshRavishankar commented on iree/compiler/Dialect/Flow/Transforms/LegalizeInputTypes.cpp
> +  if (llvm::isa<mlir::linalg::LinalgOp>(oldOp)) {
Wondering why the Linalg op will need to do something different from the logic below. If the op has valid types as assumed here it should just work?

2020-12-07 22:04 UTC, MaheshRavishankar requested changes
I am fine with this approach, but I think this might be better looked at by Ben. Will add him to reviewer list.

2020-12-08 09:27 UTC, nicolasvasilache commented
There are 2 issues right now:
1. in the case of a linalg named op, we could end up with a matmul on say i8, irrespective of the fact that the linalg op will not support that. The future-proof way is to convert from named to generic, do the rewrite and then convert back to the appropriate named form. The conversion back is not available.
2. even starting from a linalg.generic op, the pass seems to have been written quite a long time ago and currently chokes [here](https://github.com/google/iree/blob/main/iree/compiler/Dialect/Flow/Transforms/LegalizeInputTypes.cpp#L122) when encountering a linalg::Yield. The problem is that the parent op is not built yet and the verification fails. We could hack this more to circumvent this use case but it generally seems problematic that the ability to verify an op in a transient state is part of the logic to decide what to do.

I am unsure what @benvanik envisions for this pass. 
Since this was written prior to widespread use of conversions, should we consider just turning this into a conversion?  
Not sure whether that would help with the logic but it seems the majority of the code implements what conversion patterns do.

2020-12-08 09:28 UTC, nicolasvasilache commented
Note that this may also be indicative of missing OpInterface for the specific purpose of type legalization?

2020-12-08 17:09 UTC, MaheshRavishankar commented
I approve it. If @benvanik has no comments, I dont have any either :)

2020-12-08 17:10 UTC, MaheshRavishankar approved these changes

2020-12-08 17:18 UTC, benvanik commented
(looking now, I think this may just make issues harder to find later on)

2020-12-08 17:22 UTC, benvanik commented
The type converter here is what performs the i64/f64->i32/f32 truncation today. A majority of the lower level code now handles these types (or can be easily made to handle them) *except* VMLA. Since the linalg on tensor path doesn't intersect with VMLA this should be fine - and we can delete the entire pass once we are able to kill VMLA.

LGTM!

2020-12-08 17:22 UTC, benvanik approved these changes

2020-12-09 08:01 UTC, merged

2020-12-09 08:01 UTC, nicolasvasilache commented
Thanks!

2020-12-11 10:42 UTC, nicolasvasilache commented
@pifon2a