Add a new option for address sanitization with assertion message  (unimplemented feature yet)
google/iree pull request #4469
Opened 2021-01-11 23:18 UTC by inho9606

Added a new option -iree-llvm-address-sanitizer to iree-translate, but it's feature is not implemented yet.
Assertion error occurs when the new option is turned on from debug mode. On release mode, it ignores the option since it is not implemented yet.

2021-01-11 23:25 UTC, benvanik requested changes
Thanks for looking into this! We'll want to wait to start merging this until the feature is working - things like this can get particularly nasty when dealing with various platforms/compilers and will likely change a lot while trying to get it all settled. I've left some review comments to help for when that time comes, but for now we'll need to wait. Please let us know how it goes!

2021-01-11 23:25 UTC, benvanik commented on iree/compiler/Dialect/HAL/Target/LLVM/LLVMIRPasses.cpp
> +  if(options.addressSanitizer)
style: (almost) always use braces for multi-line statements in IREE code:
https://google.github.io/styleguide/cppguide.html#Conditionals

2021-01-11 23:25 UTC, benvanik commented on iree/compiler/Dialect/HAL/Target/LLVM/LLVMIRPasses.cpp
> +    assert(false && "Address Sanitization feature has not been implemented yet.");
avoid assert for expected conditions - it is generally not useful (a lot of people build and run in release mode with asserts disabled) and really difficult to debug. MLIR has `emitError`/`return failure()` to gracefully handle this with good error messages.

2021-01-11 23:25 UTC, benvanik commented on iree/compiler/Dialect/HAL/Target/LLVM/LLVMTargetOptions.cpp
> +//  if(clAddressSanitizer)
Please self-review before sending PRs to make sure you don't leave stray whitespace changes and comments :)

2021-01-11 23:25 UTC, closed without merging

2021-01-12 00:24 UTC, inho9606 commented
Thanks for the helpful comments! Sorry to create another PR after your comments. I missed your comments.

2021-01-12 00:32 UTC, benvanik commented
No problem!