Connect linalg on tensors to rest of the CPU side.
google/iree pull request #4634
Opened 2021-01-28 06:28 UTC by MaheshRavishankar

Connecting the code generated from Linalg on tensors to rest of the
CPU side requires setting the tile size (that is dynamic when tile +
distribute happens in flow level) to the static tile size that is
computed using LaunchConfig.

2021-01-28 06:30 UTC, MaheshRavishankar commented
This is ready for review. But making this a draft review. Please look at just the second commit here. The first commit is https://github.com/google/iree/pull/4597 which is ready to land, but waiting on integrate.

2021-01-28 06:34 UTC, benvanik commented
As a tip, if you hit edit you can set the base branch:
![image](https://user-images.githubusercontent.com/75337/106099535-ae245900-60ef-11eb-8d28-e5f5eb3d9931.png)

In this case to `MaheshRavishankar:linalg_on_tensors`. Then github shows only the commits added on top of that. When that branch gets merged github will automatically update this PR to point to main. It's kind of like DIFFBASE.

2021-01-28 06:40 UTC, benvanik requested changes
otherwise lgtm!

2021-01-28 06:40 UTC, benvanik commented on iree/compiler/Dialect/HAL/IR/HALOps.td
> +def HAL_YieldOp : HAL_Op<"yield", [NoSideEffect, Terminator]> {
there's already a hal.return op - let's use that instead (or, change everything to use hal.yield if that's more canonical - I think flow.return/hal.return predate the yield terminology being used upstream - but not both)

2021-01-28 06:40 UTC, benvanik commented on iree/compiler/Dialect/HAL/IR/HALOps.td
> +  let regions = (region VariadicRegion<SizedRegion<1>>:$num_workgroups_region);
naming: let's stick to `workgroup_count` - no `num_xx` - so that we are consistent here with all the other ops/attrs.

2021-01-28 17:24 UTC, MaheshRavishankar commented
> As a tip, if you hit edit you can set the base branch:
> ![image](https://user-images.githubusercontent.com/75337/106099535-ae245900-60ef-11eb-8d28-e5f5eb3d9931.png)
> 
> In this case to `MaheshRavishankar:linalg_on_tensors`. Then github shows only the commits added on top of that. When that branch gets merged github will automatically update this PR to point to main. It's kind of like DIFFBASE.
> 
> NEVERMIND: that only works on branches within the repo ;(

Would be good there was a way I can merge individual commits of sequence of commits without having to merge the whole branch....

2021-02-01 18:29 UTC, benvanik approved these changes

2021-02-01 18:58 UTC, merged