Improve Actions hygiene
google/iree pull request #5056
Opened 2021-03-10 22:45 UTC by sethvargo

👋 hello there! I'm a fellow Googler who works on projects that leverage GitHub Actions for CI/CD. Recently I noticed a large increase in our queue time, and I've tracked it down to the [limit of 180 concurrent jobs](https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration) for an organization. To help be better citizens, I'm proposing changes across a few repositories that will reduce GitHub Actions hours and consumption. I hope these changes are reasonable and I'm happy to talk through them in more detail.

- Only run GitHub Actions for pushes and PRs against the main branch of the repository. If your team uses a forking model, this change will not affect you. If your team pushes branches to the repository directly, this changes actions to only run against the primary branches or if you open a Pull Request against a primary branch.

- For long-running jobs (especially tests), I added the "Cancel previous" workflow. This is very helpful to prevent a large queue backlog when you are doing rapid development and pushing multiple commits. Without this, GitHub Actions' default behavior is to run all actions on all commits.

There are other changes you could make, depending on your project (but I'm not an expert):

- If you have tests that should only run when a subset of code changes, consider gating your workflow to particular file paths. For example, we have some jobs that do Terraform linting, but [they only run when Terraform files are changed](https://github.com/google/exposure-notifications-verification-server/blob/c4f59fee71042cf668747e599e7c769fca736554/.github/workflows/terraform.yml#L3-L11).

Hopefully these changes are not too controversial and also hopefully you can see how this would reduce actions consumption to be good citizens to fellow Googlers. If you have any questions, feel free to respond here or ping me on chat. Thank you!

2021-03-10 23:16 UTC, GMNGeoffrey requested changes
Thanks, I appreciate the effort here :-)

FTR, none of these should be long running jobs. They're all fast lint checks, but cancelling previous seems fine to me as long as *that* isn't too slow.

I can take a look at adding some path limitations

2021-03-10 23:16 UTC, GMNGeoffrey commented on .github/workflows/lint.yml
> +    - main
We do use pull requests against other branches, in which case we want this to run

2021-03-10 23:23 UTC, sethvargo reviewed
Thank you @GMNGeoffrey. Good to hear these are short-lived jobs too!

2021-03-11 01:53 UTC, GMNGeoffrey commented
I kind of want to let the actions run before merging this PR changing the actions... Looks like all GitHub actions in the Google org are totally borked :-/

2021-03-11 14:50 UTC, sethvargo commented
(And still are 13 hours later). I totally understand wanting to wait.

2021-03-11 18:34 UTC, taquitos commented
So close, just a few more 😃

2021-03-11 18:45 UTC, GMNGeoffrey commented
So the cancel action appears to take ~1s, which should be fine. That said, I think as configured it doesn't work for PRs from forks, which is basically all of them in our case: https://github.com/styfle/cancel-workflow-action#advanced-pull-requests-from-forks. Do you have data indicating that these actions are causing problems that would be solved by cancelling previous runs? If so, I think we need to iterate on the exact setup.

2021-03-11 18:53 UTC, taquitos commented
If you take a look at : https://github.com/google/iree/actions/workflows/lint.yml?query=is%3Aqueued
You can see a number of queued actions for the same step for the same PR. So I agree, we should also cancel previous runs for PRs from a fork.

2021-03-11 18:56 UTC, GMNGeoffrey commented
> If you take a look at : [google/iree/actions/workflows/lint.yml?query=is%3Aqueued](https://github.com/google/iree/actions/workflows/lint.yml?query=is%3Aqueued)
> You can see a number of queued actions for the same step for the same PR. So I agree, we should also cancel previous runs for PRs from a fork.

But I think that's only because of our current situation where everything is queued forever. In the normal case, I'm not sure that cancelling previous runs will be that useful because these checks take a few seconds each

2021-04-12 22:42 UTC, closed without merging