[CodeGen] Add a pass to canonicalize HAL interface load/store
google/iree pull request #5103
Opened 2021-03-13 13:39 UTC by antiagainst

Right now this only contains one pattern that folds tensor reshapes
into the loaded subspan.

After HAL interface materialization, outlined dispatch regions
become modules to be compiled into executables run on a specific
target. Those modules uses HAL interface binding ops to access
buffers holding input/output data. From IREE's perspective,
buffers just contain a bag of bytes. So the executable translation
is free to reinterpret the buffer in whatever shape that fits.
Therefore we can fold reshapes.

This enables turning on depthwise convolution vectorization patterns
in SPIR-V CodeGen path.

2021-03-13 15:09 UTC, MaheshRavishankar requested changes
Looks good overall, but why separate pass? I am weary having passes for specific things. This seems like it could just be a canonicalization. We are planning to use linalg on tensors as the front end for IREE anyway....

2021-03-15 22:41 UTC, antiagainst commented
> Looks good overall, but why separate pass? I am weary having passes for specific things. This seems like it could just be a canonicalization. We are planning to use linalg on tensors as the front end for IREE anyway....

Yeah. I was debating for a while where to put this actually. It's a pattern that involves 3 dialects: Flow/HAL/Linalg. It's matching against a `linalg.tensor_reshape` op. If we want to set this as a canonicalization pattern, it should be on `linalg.tensor_reshape` ops. That clearly cannot happen. Making it a canonoicalization pattern for `flow.dispatch.tensor.load` or `hal.interface.binding.subspan` ops means we need to check backwards on their uses, which is contradictory to what MLIR patterns generally do too. And it means pulling in 2 dialects as dependencies. All these sounds not proper to me. So a separate pass.

Taking another look of existing passes, we actually have another pass, `RemoveDeadMemAllocsPass`, that also just contain on simple pattern. I think one way to save yet another pass might be putting the pattern here into it and rename that pass as `BufferAllocViewCleanupPass`, given they are all performing clean ups on buffer allocations/views. We can collect more patterns in that pass later if more pop up. WDTY?

2021-03-15 22:50 UTC, MaheshRavishankar commented
> Taking another look of existing passes, we actually have another pass, `RemoveDeadMemAllocsPass`, that also just contain on simple pattern. I think one way to save yet another pass might be putting the pattern here into it and rename that pass as `BufferAllocViewCleanupPass`, given they are all performing clean ups on buffer allocations/views. We can collect more patterns in that pass later if more pop up. WDTY?

Sounds good to me.

2021-03-16 04:31 UTC, MaheshRavishankar approved these changes

2021-03-16 04:31 UTC, MaheshRavishankar commented on iree/compiler/Conversion/Common/BufferAllocViewCleanUpPass.cpp
> +    if (!loadOp.offsets().empty() || !loadOp.sizes().empty() ||
Nit: Merge this if with the others.

2021-03-16 13:18 UTC, merged