Lower `linalg.tensor_reshape` to `flow.tensor.reshape`.
google/iree pull request #5259
Opened 2021-03-30 23:35 UTC by MaheshRavishankar

Inlining reshapes into dispatch regions cause subtle issue
1) The reshape can hamper using tied operands since the type of the
   operand/result might mismatch.
2) The `subtensor` -> `tensor_reshape` causes issues during
   bufferization.

To avoid this two approaches are possible
1) Fuse reshapes with other operations as much as possible during
   fusion on linalg ops.
2) Lower reshapes to `flow.tensor.reshape` before dispatch region
   creation.

These reshapes can become no-ops later on when lowering to HAL. For
now they are lowered as copies.

2021-03-31 09:37 UTC, hanhanW approved these changes
I'm not familiar with ConvertStreamOps, but overall looks good to me.

2021-03-31 09:37 UTC, hanhanW commented on iree/compiler/Dialect/Flow/Transforms/test/convert_to_flow_tensor_ops.mlir
> +
delete the blank line

2021-03-31 09:37 UTC, hanhanW commented on iree/compiler/Dialect/HAL/Conversion/FlowToHAL/ConvertStreamOps.cpp
> +           << "cannot create adaptors for tensor reshape operands/results";
I'm confused that when do we use `rewriter.notifyMatchFailure()` and when do we use `op.emitOpError`.

I usually use `rewriter.notifyMatchFailure` when the pattern should handle it but this is not expected input or valid input. And use `return failure()` to choose the pattern to apply, e.g., i1 cases and non-i1 cases in StandardToSPIRV conversion.

2021-03-31 09:37 UTC, hanhanW commented on iree/test/e2e/models/unidirectional_lstm.mlir
> +// RUN: [[ $IREE_LLVMAOT_DISABLE == 1 ]] || (iree-run-mlir %s -iree-hal-target-backends=vulkan-spirv -function-input="1x5xf32=[0,1,0,3,4]" -iree-flow-dispatch-linalg-on-tensors -iree-codegen-spirv-ex
should be `IREE_VULKAN_DISABLE`.

```suggestion
// RUN: [[ $IREE_VULKAN_DISABLE == 1 ]] || (iree-run-mlir %s -iree-hal-target-backends=vulkan-spirv -function-input="1x5xf32=[0,1,0,3,4]" -iree-flow-dispatch-linalg-on-tensors -iree-codegen-spirv-experimental-linalg-on-tensors -function-input="1x5x2x2xf32=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]" | IreeFileCheck %s --implicit-check-not="[" --implicit-check-not="]")
```

2021-03-31 15:34 UTC, antiagainst requested changes
Haven't looked into details but blocking for now because I'd like to understand one issue:

From what I can see, the ConvertToFlowTensorOps pass is intended to be used [*after*](https://github.com/google/iree/blob/4a732d333a5ec19bb642be39c9f305223f713697/iree/compiler/Dialect/Flow/Transforms/Passes.h#L63-L66) dispatch region formation to pick up remaining ops. I think that makes sense. However, right now we are running it [*before*](https://github.com/google/iree/blob/96e9c4946399f2a0df6794252c77506e9ac1c9a5/iree/compiler/Dialect/Flow/Transforms/Passes.cpp#L212-L217). Is this change intentional or accidental? Having such sweeping change without giving fusion a first chance can cause problems: once the op is converted to flow ops, they will be barriers for fusion in the later stage.

2021-03-31 16:24 UTC, MaheshRavishankar commented
> Haven't looked into details but blocking for now because I'd like to understand one issue:
> 
> From what I can see, the ConvertToFlowTensorOps pass is intended to be used [_after_](https://github.com/google/iree/blob/4a732d333a5ec19bb642be39c9f305223f713697/iree/compiler/Dialect/Flow/Transforms/Passes.h#L63-L66) dispatch region formation to pick up remaining ops. I think that makes sense. However, right now we are running it [_before_](https://github.com/google/iree/blob/96e9c4946399f2a0df6794252c77506e9ac1c9a5/iree/compiler/Dialect/Flow/Transforms/Passes.cpp#L212-L217). Is this change intentional or accidental? Having such sweeping change without giving fusion a first chance can cause problems: once the op is converted to flow ops, they will be barriers for fusion in the later stage.

This is intentional. I am actually not changing the order of the pass here. This pass always existed (so I would not characterize this as a "sweeping change"), I am adding a pattern to it. Ideally after all the fusion passes all the reshapes have been resolved/fused away already. I have to check what this actually looks like, I am waiting for integrate before I can actually push this in.

There is a phase ordering issue that needs to be resolved. Only a limited set of operations from linalg can be converted to Flow equivalents. For example only a particular form of the subtensor operation can be lowered to flow ops. Also bufferization is much simpler without subtensor/reshape. There is particular pattern of `subtensor` -> `tensor_reshape` which lowers to `subview -> reshape` that is actually illegal due to an esoteric type issue. There is a strong requirement that there are no buffers allocated within the dispatch region. Having subtensors/tensor_reshape makes that harder to enforce.
Further existence of reshape within dispatch regions means tie-operands fails (shape mismatch), which leads to additional copies. All this is motivating this change.

I am open to moving this pass down past fusion. There are phase ordering issues there. So starting with this to see where fusion gets hurt and then making a decision.

2021-03-31 18:57 UTC, antiagainst approved these changes
Awesome, thanks for the detailed explanation! I understand the motivations. I guess eventually we might want to have two passes, one before dispatch region and one after. The patterns put into the prepass should use extra caution given its far-reaching effect. Not immediately though but worth paying attention to. Either way, worth to fixing the comment for the current pass. :)

Code looks good to me in general, so approving. 

I'd be curious on the effect of this patch to MobileNet performance b/c I recall it has quite some reshape ops there. So before you land this, would you mind to give me a heads up so I can do some profiling to see how it affects. Thanks.

2021-03-31 19:28 UTC, MaheshRavishankar commented
>
> I'd be curious on the effect of this patch to MobileNet performance b/c I recall it has quite some reshape ops there. So before you land this, would you mind to give me a heads up so I can do some profiling to see how it affects. Thanks.

Going to land this only after I look at the IR for both mobilenet and mobilebert. After all upstream patches land that help the thing a bit.
I can also wait for the fusion of elementwise PR. IIUC that should also fold away reshapes between named ops and elementwise ops. I'd like to see that happening as well.

2021-03-31 23:07 UTC, benvanik approved these changes

2021-04-09 15:51 UTC, benvanik commented
#5368 makes reshape a tied op and should let most of this outside the linalg conversion be dropped. There may still be improvements required to it that this PR will expose through real models so please let me know if you hit any issues!

2021-04-09 16:30 UTC, MaheshRavishankar commented
Awesome! Will rebase and try it out.

2021-04-09 21:43 UTC, MaheshRavishankar commented
Dropping this PR (will address the comments though). I will send out a separate PR after rebasing.

2021-04-09 21:43 UTC, closed without merging