Fold pure fill DispatchWorkgroupsOp into TensorSplatOp
google/iree pull request #5353
Opened 2021-04-08 15:16 UTC by antiagainst

Thin allows us to use DMA instead of kernels for pure data
transfers. This is another step towards performance: it
further decreases the number of dispatches for MobileNetv2
from 103 to 85, and reduced the latency by 2ms on Galaxy
S20 (Mali G77).

2021-04-08 15:19 UTC, benvanik commented
Awesome!

I think @MaheshRavishankar added some similar patterns but kept them more local to linalg-specific files - I'm not sure we want to force linalg to always happen in the flow dialect. Do you remember where they are?

2021-04-08 15:24 UTC, benvanik commented on iree/compiler/Dialect/Flow/IR/FlowOpFolders.cpp
> +    if (!storeOp || !storeOp.offsets().empty() || !storeOp.sizes().empty() ||
style: we follow google convention here and use {} around multi-line ifs please (I know LLVM doesn't require them, but they are wrong ;)

2021-04-08 15:58 UTC, MaheshRavishankar requested changes
I am not sure this is the right layering. We should then not be having the dispatch region formed in the first place. So maybe solution here is
1) For cases where the dispatch region ends up being just a fill op of a constant, not create that dispatch region
2) Add a pass post dispatch region formation to do the conversion.

I am not sure why we have the fill of this created to begin with. Do you know the root cause.

2021-04-08 16:49 UTC, antiagainst commented
> I am not sure this is the right layering. We should then not be having the dispatch region formed in the first place. So maybe solution here is
> 
> 1. For cases where the dispatch region ends up being just a fill op of a constant, not create that dispatch region
> 2. Add a pass post dispatch region formation to do the conversion.
 
To not create the dispatch region in the first place, we will need to throw in additional logic in `DispatchLinalgOnTensorsPass` to figure out such case and avoid creating the `DispatchWorkgroupsOp`. The code there is already quite complex: we first plan the fusion groups, and then create partial `DispatchWorkgroupsOp` to pull in stuff gradually and recursively and rectify it. It already happens in multiple patterns and stages. Throwing in a special case for this, we need to carefully think about it's interaction with the above logic and make sure they still function properly. It isn't clear to me why that's better than just using a well-isolated standalone canonicalization pattern to clean up, which is quite common in general. But I guess your real question might be the next:

> I am not sure why we have the fill of this created to begin with. Do you know the root cause.

Yup, it's because of convolution padding. As I commented previously on https://github.com/google/iree/pull/5102#discussion_r593903320, normally fill ops are used as the output tensor for linalg ops as initializer, where they have the same shape as the linalg op and they can be pulled into the same dispatch region as the main linalg op. Here this is for padding, where we generate linalg.fill + subtensor_insert for now. They cannot be fused and also they don't have the same shape.

2021-04-08 16:54 UTC, antiagainst commented
> I think @MaheshRavishankar added some similar patterns but kept them more local to linalg-specific files - I'm not sure we want to force linalg to always happen in the flow dialect. Do you remember where they are?

Looking at the current pass pipeline we have 

https://github.com/google/iree/blob/96e9c4946399f2a0df6794252c77506e9ac1c9a5/iree/compiler/Dialect/Flow/Transforms/Passes.cpp#L216-L224

We only have the standard canonicalization pass before outlining. If we don't want to always pick up Linalg dialect as a dependency for Flow, then probably we can put the pattern as another step in `DispatchLinalgOnTensors`. (Don't feel like to create yet another pass for it. :)

2021-04-08 16:55 UTC, benvanik commented
Agree this should go in DispatchLinalgOnTensors. In the future if there's some magic linalg.tile or whatnot that does a majority of that pass upstream then the pass logic becomes much simpler and is really linalg->flow (and could even just be a conversion in `iree/compiler/Dialect/Flow/Conversion/LinalgToFlow/`).

2021-04-08 17:42 UTC, MaheshRavishankar commented
> > I am not sure this is the right layering. We should then not be having the dispatch region formed in the first place. So maybe solution here is
> > 
> > 1. For cases where the dispatch region ends up being just a fill op of a constant, not create that dispatch region
> > 2. Add a pass post dispatch region formation to do the conversion.
> 
> To not create the dispatch region in the first place, we will need to throw in additional logic in `DispatchLinalgOnTensorsPass` to figure out such case and avoid creating the `DispatchWorkgroupsOp`. The code there is already quite complex: we first plan the fusion groups, and then create partial `DispatchWorkgroupsOp` to pull in stuff gradually and recursively and rectify it. It already happens in multiple patterns and stages. Throwing in a special case for this, we need to carefully think about it's interaction with the above logic and make sure they still function properly. It isn't clear to me why that's better than just using a well-isolated standalone canonicalization pattern to clean up, which is quite common in general. But I guess your real question might be the next:

The reason why not creating the dispatch region is better is because it relies too much on the specific structure of the dispatch workgroups op. Such patterns are inherently hard to maintain.
The setup of dispatch region creation of using root ops and fusion groups is intentionally designed to include whatever complexity and ad-hocness we want to put in right now. It is a specific heuristic that is being implemented manually. We might need other heuristics later on, and it could be easily switched out. So I am not that concerned about the complexity there cause all the complexity is contained.
I actually dont see why its an issue. You just need to check if any `fill` op is fusable with any other operation. Y

2021-04-26 16:54 UTC, antiagainst commented
Coming back to this. I see your points here. Both way works for me as long as I can get the performance bump. :) Implemented https://github.com/google/iree/pull/5614 as you suggested. I'll close this one in favor of that.

2021-04-26 16:54 UTC, closed without merging