[spirv] Properly handle subspan offset
google/iree pull request #5403
Opened 2021-04-12 20:28 UTC by antiagainst

This commit implements a pass to flatten n-D MemRef
subspan ops to 1-D MemRef ones and folds the byte
offsets on subspan ops to the consumer load/store
ops, in preparation for lowering to SPIR-V.

Addresses https://github.com/google/iree/issues/5372

2021-04-12 20:29 UTC, antiagainst commented
Note this needs https://reviews.llvm.org/D100335 and https://reviews.llvm.org/D100337.

2021-04-12 20:41 UTC, benvanik commented
fantastic work lei!

2021-04-12 21:00 UTC, MaheshRavishankar requested changes
Nice! Just a few nits.

2021-04-12 21:01 UTC, MaheshRavishankar commented
FYI @asaadaldien this has the makings of the pass to linearize multi-dimensional memrefs to 1D memrefs like we discussed today.

2021-04-13 08:33 UTC, hanhanW commented on iree/compiler/Conversion/LinalgToSPIRV/FlattenMemRefSubspanPass.cpp
> +    return memrefType.hasRank() && memrefType.getRank() <= 1;
In IREE, we wrap this with braces

2021-04-13 08:33 UTC, hanhanW commented on iree/compiler/Conversion/LinalgToSPIRV/FlattenMemRefSubspanPass.cpp
> +    return nullptr;
ditto

2021-04-13 08:33 UTC, hanhanW commented on iree/compiler/Conversion/LinalgToSPIRV/FlattenMemRefSubspanPass.cpp
> +    Value stride = builder.create<ConstantIndexOp>(loc, std::get<1>(pair));
I could misread something. But I think it is using the `strides` computed above? It is from `getStridesAndOffset(sourceType, strides, offset)`.

2021-04-13 08:33 UTC, hanhanW commented on iree/compiler/Conversion/LinalgToSPIRV/FlattenMemRefSubspanPass.cpp
> +    typename memref::LoadOp::Adaptor adaptor(operands);
I thought we need `typename` only if it is template? Can we remove it here?

2021-04-13 08:33 UTC, hanhanW commented on iree/compiler/Conversion/LinalgToSPIRV/FlattenMemRefSubspanPass.cpp
> +    if (subspanOp.byte_length()) return failure();
return `rewriter.notifyFailure`?

2021-04-13 08:33 UTC, hanhanW commented on iree/compiler/Conversion/LinalgToSPIRV/FlattenMemRefSubspanPass.cpp
> +        subspanOp.byte_length());
[optional] I recently learned that there is `ImplicitLocOpBuilder b(op.getLoc(), rewriter);`. With the builder, you don't have to pass a `Location` to the builder anymore.

2021-04-13 08:33 UTC, hanhanW commented on iree/compiler/Conversion/LinalgToSPIRV/FlattenMemRefSubspanPass.cpp
> +    if (!numBytes) return failure();
[optional] return `rewriter.notifyFailure`? I found that this is useful during debugging. Like it will tell you where does it exist.

2021-04-13 08:33 UTC, hanhanW commented on iree/compiler/Conversion/LinalgToSPIRV/FlattenMemRefSubspanPass.cpp
> +    // ops. This requires setting up conversion targets with type conversion.
```suggestion
    // ops. This requires setting up conversion targets with type converter.
```

2021-04-13 08:33 UTC, hanhanW commented on iree/compiler/Conversion/LinalgToSPIRV/FlattenMemRefSubspanPass.cpp
> +      signalPassFailure();
Do we exit if it failed?

```suggestion
      return signalPassFailure();
```

2021-04-13 15:10 UTC, antiagainst commented on iree/compiler/Conversion/LinalgToSPIRV/FlattenMemRefSubspanPass.cpp
> +    assert(isRankZeroOrOneMemRef(adaptor.memref().getType()));
Done 1. For 2 shouldn't it already be handled by `getStridesAndOffset` (with strides = [1], offset = s0)?

2021-04-13 15:15 UTC, hanhanW approved these changes

2021-04-13 16:39 UTC, MaheshRavishankar approved these changes

2021-04-13 16:39 UTC, MaheshRavishankar commented on iree/compiler/Conversion/LinalgToSPIRV/FlattenMemRefSubspanPass.cpp
> +  int64_t offset;
Ok, maybe then assert here that the `sourceType` is not a 0D memref.

2021-04-13 16:39 UTC, MaheshRavishankar commented on iree/compiler/Conversion/LinalgToSPIRV/FlattenMemRefSubspanPass.cpp
> +    if (!isRankZeroOrOneMemRef(memrefType)) return failure();
Nit: To be consistent, the similar check in the load returns a `notifyMatchFailure`. Maybe do the same here.

2021-04-14 08:19 UTC, hanhanW commented
I found that this would break using workgroup memory in Linalg on tensors.

To repro: `ree-translate --iree-mlir-to-vm-bytecode-module --iree-hal-target-backends=vulkan-spirv third_party/iree/iree/test/e2e/vulkan_specific/gemm.mlir -iree-spirv-use-workgroup-memory -iree-flow-dispatch-linalg-on-tensors -iree-codegen-spirv-experimental-linalg-on-tensors`

This also breaks conv test. There are 1D and 3D cases in the file. If you want to test it, you will have to comment those conv_1d and conv_3d. (they will be disabled in #5375 , I probably should make another change to make it easier...)

error log: https://gist.githubusercontent.com/hanhanW/55f17473630c32ac3a6f63c6e765311c/raw/07695b6a188aca70db68e22252a59c360579bf42/log

2021-04-14 15:15 UTC, antiagainst commented
> I found that this would break using workgroup memory in Linalg on tensors.

8c0afe9 should address this.

2021-04-14 15:49 UTC, merged