Add support for the rodata op in the VM to EmitC conversion
google/iree pull request #5953
Opened 2021-05-19 11:27 UTC by simon-camp

2021-05-25 18:33 UTC, marbre approved these changes
LGTM with now reusing the `PreserveCompilerHints` parts. Let's see what @benvanik says :)

2021-05-25 18:35 UTC, marbre commented
FYI, you need to rebase as `emitc/Dialect/EmitC/EmitCDialect.h` was moved to `emitc/Dialect/EmitC/IR/EmitC.h`. This was integrated into IREE with commit 4287062fca9f27a7178a2cbffcddf1defb20dabb.

2021-06-01 15:29 UTC, benvanik requested changes
awesome! this unlocks a lot! just one minor tweak and a style nit then can land

2021-06-01 15:29 UTC, benvanik commented on iree/compiler/Dialect/VM/Target/C/CModuleTarget.cpp
> +           << "IREE_VM_BUFFER_ACCESS_ORIGIN_HOST, "
this should be `IREE_VM_BUFFER_ACCESS_ORIGIN_MODULE` - that indicates that the buffer will only be available for as long as the module is loaded/initialized

2021-06-01 15:29 UTC, benvanik commented on iree/compiler/Dialect/VM/Target/ConstantEncodingUtils.cpp
> +}  // namespace VM
style: newline between function and } // namespace block

2021-06-01 15:29 UTC, benvanik commented on iree/compiler/Dialect/VM/Target/ConstantEncodingUtils.h
> +LogicalResult serializeConstantArray(Location loc, ElementsAttr elementsAttr,
style: newlines between namespace stuff and contents

2021-06-01 15:29 UTC, benvanik commented on iree/vm/ops.h
> +  return isnan(operand) ? 1 : 0;
good catch!

2021-06-09 22:38 UTC, benvanik approved these changes
two small style nits and otherwise looks great!

2021-06-09 22:38 UTC, benvanik commented on iree/vm/test/ref_ops.mlir
> +    vm.rodata private @buffer_i8 dense<[1, 2, 3]> : tensor<3xi8>
style: 2 space indent

2021-06-09 22:38 UTC, benvanik commented on iree/vm/test/emitc/module_test.cc
> +      // {assignment_ops_descriptor_, assignment_ops_create},
intended?

2021-06-09 22:38 UTC, benvanik commented on iree/vm/test/emitc/module_test.cc
> +      // {assignment_ops_descriptor_, assignment_ops_create},
(nevermind see the todo in the build file)

2021-06-09 22:38 UTC, benvanik commented on iree/compiler/Dialect/VM/Target/ConstantEncodingUtils.h
> +}  // namespace VM
nit: you got the top, but not the bottom :P

2021-06-10 14:33 UTC, merged