Update gradle to build TFLilte Java bindings AAR library
google/iree pull request #6197
Opened 2021-06-11 22:39 UTC by KoolJBlack

Process for building the AAR:

1. Start AndroidStudio. Select "Open File or Project" then choose `iree/bindings/tflite/java/gragle.build`.
2. AndroidStudio should sync the project and setup gradlew uner `iree/bindings/tflite/java`.
3. Make the project using android studio or run the build directly in terminal:
```shell
./gradlew build
```

This produces two libraries under `iree/bindings/tflite/java/build/outputs/aar`: 
* `iree-tflite-bindings-debug.aar` 
*  `iree-tflite-bindings-release.aar` 

AAR contents:
![Screen Shot 2021-06-11 at 3 33 30 PM](https://user-images.githubusercontent.com/1041731/121754922-b0011e80-caca-11eb-9355-5ac74bde56d7.png)

Include either library in another gradle project for iree tflite binding support.

2021-06-11 23:19 UTC, not-jenni approved these changes

2021-06-11 23:19 UTC, not-jenni commented
Thank you for the instructions on how to build the AAR!

2021-06-14 15:59 UTC, ScottTodd requested changes

2021-06-14 15:59 UTC, ScottTodd commented on bindings/tflite/java/build.gradle
> +            jni.srcDirs = ['org/tensorflow/lite/native']
Are these actually being included? Your screenshot of the .aar shows shared objects from https://github.com/google/iree/tree/main/iree/tools/android/run_module_app , which we _don't_ want in the archive. I'm actually pretty surprised this configuration is managing to pull sources from that directory.

2021-06-14 15:59 UTC, ScottTodd commented
> Thank you for the instructions on how to build the AAR!

Agreed :) would be even better to include them in a README or file under https://github.com/google/iree/tree/main/docs/developers

2021-06-14 21:55 UTC, ScottTodd approved these changes
👍

2021-06-14 21:55 UTC, ScottTodd commented on bindings/tflite/java/org/tensorflow/lite/native/CMakeLists.txt
> +# iree_cc_library(
can remove this (or keep as reference, but then it could go out of sync)

2021-06-14 22:39 UTC, merged