Reduce linalg convolution variants for IREE CodeGen pipelines
google/iree pull request #6614
Opened 2021-08-02 14:38 UTC by antiagainst

There are quite a few linalg convolution op variants upstream.
Handling all of them is burdensome for IREE CodeGen pieplines,
let alone that not all of them have layouts that are good for
CodeGen natively. So this commit adds a pass to reduce the
variants seen by downstream CodeGen pipelines.

For now the pass just converts conv2d ops with FHWC-flavor
constant filters into  HWCF-flavor, given that right now both
the CPU (via img2col) and GPU (via direct convolution) expect
HWCF layout filters.

The immediate use is to enable compiling MobileSSD and
PoseNet from TOSA path in IREE.

2021-08-02 14:52 UTC, NatashaKnk approved these changes

2021-08-02 22:37 UTC, MaheshRavishankar requested changes
Why are we doing this way rather than just adding support for the conv types?

2021-08-03 13:52 UTC, antiagainst commented
> Why are we doing this way rather than just adding support for the conv types?

FHWC layout filters won't be good for the direct convolution approach we have on Mali GPU---it has the input channel as the innermost, which means we cannot have adjacent GPU threads reading consecutive memory ranges for effective loading of the filters. We can do that with HWCF layout given F is the output channel which is parallel. For CPU, IIUC it isn't as simple as just register this op somewhere too; we need to have custom logic for lowering, like what we have for the existing HWCF layout one.

2021-08-03 14:20 UTC, benvanik commented
probably naive question: why do we care about the user-specified layout of the data at all? could we insert a transpose before/after, have it fuse with producers/consumers, and always hit a fast path we do support? I feel like the transform being done on the constant inline is also sketchy - couldn't that be inserted as a transpose op and let normal constant folding take care of it? (this PR presumes it's only ever constants, which I'd really like to avoid - it makes it harder to bring up new models as we have to rediscover all of these things if we go off the happy path - it'd be really nice not to repeat the mistakes of tflite with respect to hardcoding special paths while we bring up our replacement to tflite ;)

2021-08-03 15:13 UTC, antiagainst commented
Transposing before and after and fusing with producers/consumers is nice but they cannot always reliably work, at least in the near future. Like we still don't have operand fusion universally enabled and it's not a high priority considering tons of other tasks to work on ;); and these metadata-ish ops can cause quite some pains for dispatch region formation and sometimes cause additional copies that either break compilation or cause additional overheads. (I recall the fun trying to handle reshape for initial MobileNet bring up and perf improvement.)

The main drive of this change is to enable some additional models from TOSA path so we can have more model coverage and benchmark numbers for Stella's upcoming report, other than our old good friend MobileNetV2 and MobileBERT. :)

2021-08-03 15:17 UTC, benvanik commented
I think that's fine - while neither solution is perfect one is certainly more scalable :)
It's easier to not do the inline constant transpose and just insert the transpose - if we don't fold that, we 100% should fold that and it's better to move the code to a folder than it is to have it inlined here. If in the future that becomes a non-constant value the same improvements we have to make to fuse transposes will be the only thing needed and no one will have to touch this code.

2021-08-03 16:52 UTC, MaheshRavishankar commented
> > Why are we doing this way rather than just adding support for the conv types?
> 
> FHWC layout filters won't be good for the direct convolution approach we have on Mali GPU---it has the input channel as the innermost, which means we cannot have adjacent GPU threads reading consecutive memory ranges for effective loading of the filters. We can do that with HWCF layout given F is the output channel which is parallel. For CPU, IIUC it isn't as simple as just register this op somewhere too; we need to have custom logic for lowering, like what we have for the existing HWCF layout one.

But this is happening at the flow level, which means all backends are doing this. Does this make sense for all backends? (dont know, asking). Also is this about performance on about correctness. If this is about just being able to run these there are a different set of things to address.
Mainly concerned that doing this so early means we are over-comitting to one way of doing this. It is definitely not clear to me if this is the right approach long-term.
At the very least, could this happen even before it hits IREE? Pushing this kind of heuristics to the front end is not great either, but at least doesnt overcommit us to this path within the core compiler. Rather have those "unhandled" or "gives poor performance" than a short term solution that is specific to a device.

> Like we still don't have operand fusion universally enabled and it's not a high priority considering tons of other tasks to work on ;);

This should be a priority. I have been wanting to get to this for a week or so now. Distracted with things that were not on my initial task list. Any help on that would be great!

2021-08-31 21:15 UTC, antiagainst commented
We have the intended TFLite/TOSA models benchmarked now; so don't need this anymore. :)

2021-08-31 21:15 UTC, closed without merging