Merge SPIR-V dynamic pipeline into main
google/iree pull request #6793
Opened 2021-08-18 18:49 UTC by antiagainst

2021-08-18 19:58 UTC, MaheshRavishankar approved these changes

2021-08-19 16:39 UTC, MaheshRavishankar requested changes

2021-08-19 16:39 UTC, MaheshRavishankar commented on iree/compiler/Codegen/SPIRV/KernelDispatchUtils.cpp
> +  for (int i = 1; i < std::min(3u, loopDepth); ++i) {
Dont want to hard code this. I have a utility method `getPartitionedLoops` which returns which loops are partitioned. Could we use that instead?

2021-08-19 18:47 UTC, antiagainst commented
#6777 is landed and it's the same thing. So closing this one.

2021-08-19 18:47 UTC, closed without merging