[WIP] Limit fusion to ops with single uses to avoid duplication
google/iree pull request #7103
Opened 2021-09-20 19:53 UTC by ThomasRaoux

2021-09-20 20:36 UTC, ThomasRaoux commented
Now that the noise problem are fixed in the benchmark, limiting the fusion to not duplicate ops seems to not cause regressions. So sending it for review.

2021-09-20 20:42 UTC, MaheshRavishankar requested changes

2021-09-20 20:42 UTC, MaheshRavishankar commented on iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
> +        if (llvm::any_of(
WHy this?

2021-09-21 05:13 UTC, MaheshRavishankar approved these changes

2021-09-21 05:13 UTC, MaheshRavishankar commented on iree/compiler/Dialect/Flow/Transforms/DispatchLinalgOnTensors.cpp
> +        if (llvm::any_of(
I have to see some examples here. These heuristics have become really long and patch-worky. Need to resolve this and do some house cleaning here.

Ill stamp this for now.

2021-09-21 18:17 UTC, antiagainst commented
FYI: I fixed a bug that caused benchmark commenting not working with https://github.com/google/iree/pull/7112. So you may want to merge the latest `main` branch to give it a go. Sorry about the inconvenience!

2021-09-21 18:45 UTC, ThomasRaoux commented
> FYI: I fixed a bug that caused benchmark commenting not working with #7112. So you may want to merge the latest `main` branch to give it a go. Sorry about the inconvenience!

Thanks, I rebased

2021-09-22 20:01 UTC, ThomasRaoux commented
I fixed the performance issue on MobileNetV3, the problem was that broadcast ops were not getting fused anymore so I changed the code to make sure broadcast are fused even if they have multiple uses. Looking at the remaining regressions it looks like noise to me. Looks like the last result from `MobileSSD` is an outlier and the perf I get matches the rest of the measures. The DeepLabV3 perf on mali is the only one I'm unsure about, I'll check if it is a real regression.

2021-09-22 20:10 UTC, ThomasRaoux commented
Compiling DeepLabV3 model locally my patch doesn't change the output at all so it cannot change performance. I think it should be fine to push this. @antiagainst, @MaheshRavishankar let me know if you have any concerns.

2021-09-22 20:15 UTC, antiagainst commented
SGTM. Thanks for double checking it, Thomas!

2021-09-22 23:34 UTC, merged