Rework the way std math ops are used from C and C++.
google/iree pull request #7604
Opened 2021-11-11 06:36 UTC by stellaraccident

This attempts to do the right thing from a C/C++ namespace perspective and then works around brokenness in old versions of libstdc++ that keep us from doing the complete right thing.

Fixes #7603

2021-11-11 08:45 UTC, marbre approved these changes
I don't really like that we need a fix because of a test written in C++. Nevertheless, I really like the fix itself!

2021-11-11 15:29 UTC, benvanik requested changes
Yeah we don't want this this C++ in there - the file should be pure C and these kind of changes make it really brittle - we'll just be broken in different places and play whackamole as with the complexity of this stuff we'll never be able to safely make changes.

The root of the issue is that emitc generates all its code in a .h - it should only declare a function in the .h and all the rest should be in a .c that's compiled independently. No C++ file should ever include this header.

Since this is just a low-level test for emitc until we fix that a user hitting the issue can just disable emitc with the cmake flag.

2021-11-11 15:37 UTC, benvanik commented
Another thing to try, since you have a setup you can test, is moving the header in the test - right now it's at the top before any C++ includes, but it may play better if it is below them: https://github.com/google/iree/blob/89e9530b79e7946e04ccde9b0ac226a3f98dbffa/iree/samples/emitc_modules/add_module_test.cc

2021-11-11 16:25 UTC, benvanik commented
(here's an issue for making emitc modules safe to use: https://github.com/google/iree/issues/7605)

2021-11-11 16:46 UTC, stellaraccident commented
If this isn't supposed to be a thing we do, I'll just add a `using namespace std` to that one test. That's what I had, but I convinced myself this was a real use case and did a real fix. If it's not, I'll just do the simple thing until emitc can be layered as desired.

2021-11-12 05:58 UTC, stellaraccident commented
PTAL

2021-11-12 05:58 UTC, benvanik approved these changes

2021-11-12 06:22 UTC, merged