IREEComprehensiveBufferize: InitTensorOp Elimination
google/iree pull request #7647
Opened 2021-11-12 02:40 UTC by matthias-springer

#7646 should be addressed first.

2021-11-12 02:41 UTC, matthias-springer commented
Is there such a thing as "dependent pull requests" on Github? There should be only one commit in this PR.

2021-11-20 03:13 UTC, matthias-springer commented
Rebased and updated the pull request.

2021-11-20 04:31 UTC, MaheshRavishankar requested changes
Minor comment.

2021-11-22 22:33 UTC, MaheshRavishankar approved these changes

2021-11-22 23:44 UTC, merged