Make the vectorization decision local to the dispatch region.
google/iree pull request #7836
Opened 2021-12-08 19:07 UTC by hanhanW

2021-12-08 19:10 UTC, MaheshRavishankar requested changes
One minor comment.

2021-12-08 19:10 UTC, MaheshRavishankar commented on iree/compiler/Codegen/LLVMCPU/LLVMCPULowerExecutableTarget.cpp
> +static bool lowerToVectors(IREE::HAL::ExecutableVariantOp variantOp) {
Could you refactor this a little bit to have a method in `Utils` and say `isVMVX`. Use that to check for vectorization here.

2021-12-09 21:45 UTC, hanhanW commented
@MaheshRavishankar I remember that you'll need `isVMVXBackend` method in your changes. If this PR looks good, I think we can land it.

2021-12-09 22:28 UTC, MaheshRavishankar approved these changes

2021-12-09 22:28 UTC, merged