[EmitC] Run canonicalizer after the conversion
google/iree pull request #8336
Opened 2022-02-15 12:05 UTC by simon-camp

In order to make this work allocation of uninitialized stack variables is now done through calls to `iree_alloca`. This shrinks the [static library C sample](https://github.com/google/iree/blob/04bd09470ea92af9b5172093eee05835fedb61d1/iree/samples/static_library/CMakeLists.txt#L153) by ~900 bytes in release mode.

Progress on #6737

2022-02-15 14:52 UTC, marbre commented on iree/compiler/Dialect/VM/Conversion/VMToEmitC/ConvertVMToEmitC.cpp
> +                      /*type=*/builder.getI32Type(),
```suggestion
                      /*type=*/builder.getIndexType(),
```

2022-02-15 15:12 UTC, marbre approved these changes
Awesome! Just one suggestion with regard to the return type of `sizeof()`.

2022-02-15 15:56 UTC, benvanik requested changes
If I'm reading this right, it's alloca'ing each variable independently? alloca is practically dangerous for a lot of reasons so it'd be a good idea to break down how this is used exactly.

On the more benign side it can be very slow depending on compilation mode/runtime (MSVC and ASAN do stack checks each time), while on the more heisenbug side it can result in stack overflows if there's any control flow as alloca has no free (you just keep growing stack until the function returns), and on the potentially catastrophic side behavior is undefined on some platforms if you blow the stack (on Windows you'll get a check failure, while on linux you'll just create a very wide exploit vector for arbitrary code execution). There are cases it's useful but it usually requires careful consideration of the environment (not in branches, no calls to long running functions, no recursion, etc) and parameters (guarded sizes on anything that may originate from user input, etc), which I'm not sure we can do here.

It'd be worth discussing the motivation for this so we can find some other alternatives (I don't readily see how alloca is related to canonicalization so am just speculating).

2022-02-15 20:04 UTC, marbre commented
The problem is that `emitc.constant` ops are used in a way so that they are not constant. E.g. there is code similar to
```mlir
  func @myfunc() {
    %0 = "emitc.constant"() {value = 0 : i32} : () -> i32
    %1 = "emitc.constant"() {value = 0 : i32} : () -> i32
    %2 = emitc.apply "&"(%0) : (i32) -> !emitc.opaque<"int32_t*">
    %3 = emitc.apply "&"(%1) : (i32) -> !emitc.opaque<"int32_t*">
    emitc.call "write_to_ptrs"(%2, %3) : (!emitc.opaque<"int32_t*">, !emitc.opaque<"int32_t*">) -> ()
    return
  }

```
which `mlir-opt --canonicalize` transforms into
```mlir
  func @myfunc() {
    %0 = "emitc.constant"() {value = 0 : i32} : () -> i32
    %1 = emitc.apply "&"(%0) : (i32) -> !emitc.opaque<"int32_t*">
    %2 = emitc.apply "&"(%0) : (i32) -> !emitc.opaque<"int32_t*">
    emitc.call "write_to_ptrs"(%1, %2) : (!emitc.opaque<"int32_t*">, !emitc.opaque<"int32_t*">) -> ()
    return
  }
```
So the actual challenge is to model stack variables. Generating `emitc.call` ops to `alloca()` seemed reasonable, but you're right that using `alloca()` is dangerous. Therefore, we probably need something else to model on the EmitC dialect side as well as code that can be emitted as valid C *and* C++.

2022-02-16 12:38 UTC, marbre commented
I'll propose an `emitc.variable` op which should fix most of the problems we're currently facing.

2022-03-01 13:12 UTC, simon-camp commented
Superseded by #8424 .

2022-03-01 13:12 UTC, closed without merging