mmt4d flag
google/iree pull request #8402
Opened 2022-02-24 02:45 UTC by GMNGeoffrey

- Allow MMT4D construction to be enabled in iree-translate
- Switch off MultiOpNest
- Use iree-translate flag in MMT4D tests

2022-02-24 17:23 UTC, MaheshRavishankar requested changes
Just some high level comments that I'd hope will get some traction.

2022-02-24 17:23 UTC, MaheshRavishankar commented on iree/compiler/Dialect/Flow/Transforms/ConvertLinalgMatmulToMmt4D.cpp
> +  explicit ConvertLinalgMatmulToMmt4DPass(CustomKernelsTargetInfo targetInfo)
So I have always had a problem with `CustomKernelsTargetInfo` struct. This seems to be a side-channel data structure that is trying to bridge an existing gap in MLIR w.r.t setting pass options when adding a pass to a pipeline. I have been trying to follow what I outlined in this issue (https://github.com/llvm/llvm-project/issues/53145) so that if and when it gets fixed upstream it would be a simple things to just pull into IREE. Basically the `CustomKernelsTargetInfo` needs to be broken up as `Option<...>` of the pass and then control it...

2022-02-24 17:23 UTC, MaheshRavishankar commented on iree/compiler/Dialect/Flow/Transforms/Passes.cpp
> +  if (clMmt4dTargetOptions != "") {
use `clMmt4dTargetOptions.empty()`?

2022-02-24 18:56 UTC, GMNGeoffrey commented on iree/compiler/Dialect/Flow/Transforms/Passes.cpp
> +  if (clMmt4dTargetOptions != "") {
Done, thanks

2022-02-24 19:04 UTC, GMNGeoffrey commented on iree/compiler/Dialect/Flow/Transforms/ConvertLinalgMatmulToMmt4D.cpp
> +  explicit ConvertLinalgMatmulToMmt4DPass(CustomKernelsTargetInfo targetInfo)
Not sure if you didn't finish your sentence there Mahesh. You'd prefer to see this as a struct with the strings for the pass options, is that correct? I think the way to reconcile that with what Benoit is saying is to actually make the Options the true types that we want them to be with the parsing happening as part of the llvm command line parsing infrastructure. I can take a swing at that, but I suspect it will be non-trivial...

2022-02-24 20:00 UTC, MaheshRavishankar commented on iree/compiler/Dialect/Flow/Transforms/ConvertLinalgMatmulToMmt4D.cpp
> +  explicit ConvertLinalgMatmulToMmt4DPass(CustomKernelsTargetInfo targetInfo)
So if you look at the bug I linked, the options to the pass  are list `Option<...>`that are regular MLIR pass options. The struct has a mirror of all these options. 
So if you have two options
```
Option<int> foo;
Option<bool> bar;
```

the struct will have

```
struct PassOptionsStruct {
  int fooVal;
  bool barVal;
};
```

Then the pass has a constructor

```
struct MyPass {
  MyPass(const PassOptionsStruct &options) {
      this->foo.assign(options.fooVal);
      this->bar.assign(options.barVal);
  }
}
```

This is all boiler plate, and could all be auto-generated.

As Benoit mentioned, the divergence is the use of strongly typed enums. I think there needs to be a separate RFE on MLIR to allow  pass option values to `EnumAttr` where the verification can happen while parsing the option itself. In the absence of this, there is separate methodology that is being built here to tide over the missing pieces. Its perfectly fine for you guys to say you dont want to tackle this now, and you want to stick with this existing approach because it does  serve some purpose. I am more concerned about end state (it is fine for now). Lets say we keep building on this and we have a custom way of parsing the (complex?) kernel configuration settings, for someone looking at this externally, it is an additional thing they need to know/understand vs. "this is just different MLIR pass options of this pass".

W.R.T. the same options being used on different passes, thats a kind of coupling across the stack that is something that triggers my spidey sense, but I dont have a concrete thing to say one way or another. (The thing with options on `iree-translate` is also a known issue in MLIR. Another reason to not add more things to `iree-translate` cause hopefully when Mehdi and co. start paying attention to pipeline support in MLIR this things will get fixed to a better state. The case here might be justified based on pain points in benchmarking infra)

Anyway, more than anything just wanted to say this way of handling options gives me pause, but I do see there is no great alternative.

2022-02-24 20:00 UTC, MaheshRavishankar approved these changes

2022-02-24 20:07 UTC, GMNGeoffrey commented on iree/compiler/Dialect/Flow/Transforms/ConvertLinalgMatmulToMmt4D.cpp
> +  explicit ConvertLinalgMatmulToMmt4DPass(CustomKernelsTargetInfo targetInfo)
Yeah I definitely see your concern here and I agree that not inventing our own custom thing here has a fair amount of value. Let me play around a bit with the options parsing to see if I can keep our type safety while fitting into the common format. In support of your point about the dangers of coupling options for passes at different levels of the stack, the intrinsics "feature" here is only used in the vector custom kernels, not in the linalg->mmt4d

2022-02-24 23:51 UTC, GMNGeoffrey commented on iree/compiler/Dialect/Flow/Transforms/ConvertLinalgMatmulToMmt4D.cpp
> +  explicit ConvertLinalgMatmulToMmt4DPass(CustomKernelsTargetInfo targetInfo)
Ok, I tried it out and ran into a few issues:

1. MLIR pass options don't support `cl::bits` bitfield options, which is really what we want for features
2. Messing with this requires a lot of guessing about C++ within tablegen
3. There's way too much template metaprogramming cleverness for me to grok how to extend things. I got features parsing as list of enums, but that's not really what we want.

I filed https://github.com/llvm/llvm-project/issues/54069 for `bits` support in MLIR pass options, but I'm going to land this as-is for now

2022-02-24 23:55 UTC, merged

2022-02-25 00:10 UTC, MaheshRavishankar commented on iree/compiler/Dialect/Flow/Transforms/ConvertLinalgMatmulToMmt4D.cpp
> +  explicit ConvertLinalgMatmulToMmt4DPass(CustomKernelsTargetInfo targetInfo)
Thanks for looking into it. I suspect we will have to revisit this soon.

2022-02-25 00:16 UTC, GMNGeoffrey commented on iree/compiler/Dialect/Flow/Transforms/ConvertLinalgMatmulToMmt4D.cpp
> +  explicit ConvertLinalgMatmulToMmt4DPass(CustomKernelsTargetInfo targetInfo)
Yeah me too. The other thing to revisit is whether we can just kill these pass options entirely though, which would have other benefits as well :-) I think that requires a meeting with me, you, Benoit, and Ben though.

2022-02-25 01:56 UTC, bjacob commented
🥳