Enable compilation and runtime roundtrip tests for microbenchmarks
google/iree pull request #8904
Opened 2022-04-14 21:06 UTC by hanhanW

2022-04-14 21:07 UTC, MaheshRavishankar approved these changes

2022-04-14 21:11 UTC, hanhanW commented
@pzread you can consider to add microbenchmarks to this folder. For convolution cases, we don't have to start with mhlo level. We can add linalg_conv_xxx.mlir files instead.

2022-04-14 21:17 UTC, antiagainst requested changes
Wait. I think this will by default put all microbencmarks to tests and gotten invoked when we `ctest`? Can we make these opt-in and not run by default when running tests?

2022-04-14 21:19 UTC, hanhanW commented
> Wait. I think this will by default put all microbencmarks to tests and gotten invoked when we `ctest`? Can we make these opt-in and not run by default when running tests?

Yes, you're right. It's sounds good to me. How do I make them opt-in and not run by default?

2022-04-14 21:26 UTC, antiagainst commented
Not sure ctest supports optionality.. Could use a CMake option like `IREE_BUILD_MICROBENCHMARKS` to guard against this I think.

2022-04-14 21:29 UTC, MaheshRavishankar commented
> Wait. I think this will by default put all microbencmarks to tests and gotten invoked when we `ctest`? Can we make these opt-in and not run by default when running tests?

Just curious why not run these tests? As far as I understand, they are just making sure these compile and run, and it should be a small fraction of the  time taken by other tests (like the model tests). So I think it is OK to be added by default?

2022-04-14 21:30 UTC, hanhanW commented
After thinking a while, maybe it's fine to put them to default ctest? The purpose is to test compilation and runtime for the ops. We're not running microbenchmarks in ctest.

2022-04-14 23:34 UTC, antiagainst commented
Time to run these microbenchmarks is indeed one concern. For stable benchmarks we tend to include large-shaped ops. Also we want to consider many variants. It can adds up quickly. Looks [right now](https://source.cloud.google.com/results/invocations/9f8f6d63-80b4-4192-89f6-188e37fc6d7c/targets/iree%2Fgcp_ubuntu%2Fcmake%2Flinux%2Fx86-swiftshader%2Fpresubmit/log) the existing ones is taking ~100s, while model tests taking ~150s. So they are at similar levels of latency already. I think we are looking to include further stuff here.

More importantly (micro)benchmarks are not tests. Tests are meant for correctness (including those model tests). Each checks a different feature or from a different angle. Typically we don't check in multiple tests covering the same thing. Microbenchmarks actually does that by just focusing one single op and varying its shape. There is little additional coverage here to warrant always running them in each `ctest` invocation for everybody during daily development.

I do see the needs of keeping these IRs up to date and able to compile though. (Given that there is no verifying the output at all right now, I'm not sure we need to actually run them.) It happens at a quite low frequency and only after some integration. If we want to guard against such stale IR cases, using CI is enough for it IMO. So making it optional and default to off and enable for CIs would cover that, and we don't need to pay the cost during daily development after each `ctest` invocation. :)

2022-04-14 23:45 UTC, MaheshRavishankar commented
> Time to run these microbenchmarks is indeed one concern. For stable benchmarks we tend to include large-shaped ops. Also we want to consider many variants. It can adds up quickly. Looks [right now](https://source.cloud.google.com/results/invocations/9f8f6d63-80b4-4192-89f6-188e37fc6d7c/targets/iree%2Fgcp_ubuntu%2Fcmake%2Flinux%2Fx86-swiftshader%2Fpresubmit/log) the existing ones is taking ~100s, while model tests taking ~150s. So they are at similar levels of latency already. I think we are looking to include further stuff here.
> 
> More importantly (micro)benchmarks are not tests. Tests are meant for correctness (including those model tests). Each checks a different feature or from a different angle. Typically we don't check in multiple tests covering the same thing. Microbenchmarks actually does that by just focusing one single op and varying its shape. There is little additional coverage here to warrant always running them in each `ctest` invocation for everybody during daily development.
> 
> I do see the needs of keeping these IRs up to date and able to compile though. (Given that there is no verifying the output at all right now, I'm not sure we need to actually run them.) It happens at a quite low frequency and only after some integration. If we want to guard against such stale IR cases, using CI is enough for it IMO. So making it optional and default to off and enable for CIs would cover that, and we don't need to pay the cost during daily development after each `ctest` invocation. :)

These are indeed meant for correctness (and by the above argument should run CIs). The point is these micro benchmarks should always compile + run. Right now these are not "testing the result" cause they are bigger size inputs and outputs and testing the result for these sizes is hard. I think it is useful to have the test compile + run (run is just to make sure it doesnt say segfault at runtime or something like that) even if these tests dont have correctness included. 

100s is a lot actually, but it is not that much. I think its worth having these.

2022-04-15 00:56 UTC, dcaballe commented
Interestingly @MaheshRavishankar, @hanhanW and I had exactly the same discussion a few days ago :).  I think I align with what @antiagainst said: testing and benchmarking should be "independent". Otherwise, testing will impose unnecessary runtime constraints on what we can benchmark. Running the benchmarks won't provide too much value from a testing perspective since we are not validating the output. Yes, we would know if the benchmark is crashing or not but that's only marginal information. We can mess up the IR in many ways that won't lead to a runtime crash. What I've seen in other projects is that benchmarks are accompanied by representative e2e tests where the output is checked and that run within a more reasonable time budget. Even e2e tests may become problematic: https://discourse.llvm.org/t/check-mlir-times-examples-standalone-testing-time/6073 :)

I think enabling benchmarks with a cmake flag could be a good first step, as suggested above.

Hopefully that helps!

2022-04-15 01:16 UTC, MaheshRavishankar commented
> Interestingly @MaheshRavishankar, @hanhanW and I had exactly the same discussion a few days ago :). I think I align with what @antiagainst said: testing and benchmarking should be "independent". Otherwise, testing will impose unnecessary runtime constraints on what we can benchmark. Running the benchmarks won't provide too much value from a testing perspective since we are not validating the output. Yes, we would know if the benchmark is crashing or not but that's only marginal information. We can mess up the IR in many ways that won't lead to a runtime crash. What I've seen in other projects is that benchmarks are accompanied by representative e2e tests where the output is checked and that run within a more reasonable time budget. Even e2e tests may become problematic: [discourse.llvm.org/t/check-mlir-times-examples-standalone-testing-time/6073](https://discourse.llvm.org/t/check-mlir-times-examples-standalone-testing-time/6073) :)
> 
> I think enabling benchmarks with a cmake flag could be a good first step, as suggested above.
> 
> Hopefully that helps!

Well there is performance tracking and there is testing. They are indeed independent, but making sure things that are needed for performance tracking are "not broken" should very much be part of testing. We could maybe add this as part of post-submit testing if 100s of testing is too onerous (no one needs/should run the test all the time. You probably need to run it once locally to verify, or just let CI run it which is what I do, so 100s is very doable). Right now we are relying on post-submit to catch places where things are broken and either revert or fix forward on those errors. We could do that for these tests too if there is a place in the post-submit CI these could slot in.
Re: full correctness testing, of course that would be better, but is hard to do for large tensors. At least a runtime crash tells you something is broken (like maybe too much stack allocation, etc.). Hopefully other smaller unit tests are enough to catch correctness issues. 

I still dont see a reason to not have these tests checked in. Maybe post-submit is an option.

2022-04-15 01:29 UTC, hanhanW commented
I understand that putting this to default adds overheads for everybody during daily development. It makes sense to have an option to control it. People who care it can turn on the option themselves. We can ask CI to test it.

The current revision only enables compilation, but not runtime. It's okay to me because I believe they are all covered in our unit tests and integration tests. We can add runtime tests to CI if we run into issues.

Do we have preference to run it on which CI bot?
I could not find how to put it to other presubmit bots, so I temporary add it to `linux/x86-swiftshader-asan`.

2022-04-15 02:02 UTC, antiagainst approved these changes
LGTM, just some additional nits.

2022-04-15 02:04 UTC, antiagainst commented on build_tools/kokoro/gcp_ubuntu/cmake/linux/x86-swiftshader-asan/build.sh
> +  "-DIREE_BUILD_MICROBENCHMARKS=ON"
`cmake/build_android_benchmark.sh` runs on pull requests.

2022-04-15 02:12 UTC, antiagainst commented
> I still dont see a reason to not have these tests checked in. Maybe post-submit is an option.

Having them checked by CI is fine to me; either presubmit or postsubmit works. I was saying it's better to allow the optionality so that folks can choose to avoid running these in the daily development workflow, as they are not the same as the other tests and we have correctness coverage for these ops in e2e/ directory. :)

2022-04-15 21:25 UTC, merged

2022-04-15 21:57 UTC, MaheshRavishankar commented
> > I still dont see a reason to not have these tests checked in. Maybe post-submit is an option.
> 
> Having them checked by CI is fine to me; either presubmit or postsubmit works. I was saying it's better to allow the optionality so that folks can choose to avoid running these in the daily development workflow, as they are not the same as the other tests and we have correctness coverage for these ops in e2e/ directory. :)

Understood. I guess personally I dont run into the issue since I have vscode setup so I can run different test suites. So I rarely run all tests (mostly cause we have a resnet test in the e2e/models that takes as much time as all other tests combined in debug builds)